language: ruby
rvm:
  - 2.3.1

addons:
  postgresql: "9.3"

before_install:
  cp config/database.travis.yml config/database.yml

before_script:
  - psql -c 'create database travis_ci_flashcards;' -U postgres